### ISSUE TITLE
xCode 9: Deletion not working

### ISSUE THREAD

**Issue by marshallino16** [flybrotherlixiang/FBXCodeExtension#2]
In **xCode 9**, duplicate feature works perfectly but the deletion does not.

**Comment by flybrotherlixiang** [comment]
@marshallino16 Working on it, thanks for reporting the issue.

But the Xcode 9 beta version won't let me debug extension smoothly (It will crash at some point when debugging), I'll probably look into it after the official release of Xcode 9.

**Comment by flybrotherlixiang** [comment]
@marshallino16 XCode 9 official release works fine
